### ISSUE TITLE
"RuntimeError: link failure" when trying to run examples or editor

### ISSUE THREAD

**Issue by Alexander15M** [kitao/pyxel#122]
Hello. I get the following error when a try to run any pyxel example, and the editor.

```
Traceback (most recent call last):
  File "02_jump_game.py", line 155, in <module>
    App()
  File "02_jump_game.py", line 8, in __init__
    pyxel.init(160, 120, caption="Pyxel Jump")
  File "D:\ProgramData\Anaconda3\lib\site-packages\pyxel\__init__.py", line 296, in init
        App(module, width, height, caption, scale, palette, fps, border_width, border_color)
      File "D:\ProgramData\Anaconda3\lib\site-packages\pyxel\app.py", line 169, in __init__
        self._renderer = Renderer(width, height)
      File "D:\ProgramData\Anaconda3\lib\site-packages\pyxel\renderer.py", line 48, in __init__
        self._draw_shader = GLShader(DRAWING_VERTEX_SHADER, DRAWING_FRAGMENT_SHADER)
      File "D:\ProgramData\Anaconda3\lib\site-packages\pyxel\gl_wrapper.py", line 12, in __init__
        shaders.compileShader(fragment_shader, gl.GL_FRAGMENT_SHADER),
      File "D:\ProgramData\Anaconda3\lib\site-packages\OpenGL\GL\shaders.py", line 197, in compileProgram
        program.check_linked()
      File "D:\ProgramData\Anaconda3\lib\site-packages\OpenGL\GL\shaders.py", line 122, in check_linked
        glGetProgramInfoLog( self ),
    RuntimeError: Link failure (0): b'' 
```   

   

The windows does open for a moment before the error.

I'm running Windows 7 and Python 3.6.5, thanks for any help.

**Comment by kitao** [comment]
New version of Pyxel (1.1.1) replaced its rendering engine entirely.
So this issue should not occur anymore.
