### ISSUE TITLE
Crash when minimize

### ISSUE THREAD

**Issue by GitRenhl** [kitao/pyxel#144]
**Describe the bug**
When I minimize my game it crash and show me this error.

**To Reproduce**
1. Run your program
2. Minimize program

**Screenshots**
```py
Traceback (most recent call last):
  File "g:\Python2019\physics\main.py", line 150, in <module>
    pyxel.run(app.update, app.draw)
  File "C:\Users\(Username)\AppData\Local\Programs\Python\Python36\lib\site-packages\pyxel\app.py", line 294, in run
    main_loop()
  File "C:\Users\(Username)\AppData\Local\Programs\Python\Python36\lib\site-packages\pyxel\app.py", line 287, in main_loop
    self._draw_frame()
  File "C:\Users\(Username)\AppData\Local\Programs\Python\Python36\lib\site-packages\pyxel\app.py", line 520, in _draw_frame
    self._border_color,
  File "C:\Users\(Username)\AppData\Local\Programs\Python\Python36\lib\site-packages\pyxel\renderer.py", line 83, in render
    gl.glDisable(gl.GL_VERTEX_PROGRAM_POINT_SIZE)
  File "C:\Users\(Username)\AppData\Local\Programs\Python\Python36\lib\OpenGL\error.py", line 232, in glCheckError
    baseOperation = baseOperation,
OpenGL.error.GLError: GLError(
	err = 1281,
	description = b'nieprawid\xb3owa warto\x9c\xe6',
	baseOperation = glDisable,
	cArguments = (GL_VERTEX_PROGRAM_POINT_SIZE,)
)
```
**Desktop:**
OS: Windows 10
Python: 3.6, 3.7

**Comment by kitao** [comment]
I've released the new version of Pyxel, 1.1.1.
Its engine is entirely rewritten. So could you check the same issue happen on the new Pyxel?
