### ISSUE TITLE
ImportError: Failed to load GLFW3 shared library.

### ISSUE THREAD

**Issue by tilesentik** [kitao/pyxel#160]
**Describe the bug**
Getting error on first code sample of the README.md file.

**To Reproduce**
1. test.py
```python
import pyxel

pyxel.init(160, 120)

def update():
    if pyxel.btnp(pyxel.KEY_Q):
        pyxel.quit()

def draw():
    pyxel.cls(0)
    pyxel.rect(10, 10, 20, 20, 11)

pyxel.run(update, draw)
```
2. console output  for python 3.6
``` python
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import pyxel
  File "/usr/local/lib/python3.6/dist-packages/pyxel/__init__.py", line 4, in <module>
    from . import constants  # type: ignore
  File "/usr/local/lib/python3.6/dist-packages/pyxel/constants.py", line 1, in <module>
    import glfw
  File "/usr/local/lib/python3.6/dist-packages/glfw/__init__.py", line 34, in <module>
    raise ImportError("Failed to load GLFW3 shared library.")
ImportError: Failed to load GLFW3 shared library.
```

3. console output  for python 3.7
``` python
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import pyxel
ModuleNotFoundError: No module named 'pyxel'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 24, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'

Original exception was:
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import pyxel
ModuleNotFoundError: No module named 'pyxel'
```
I'm running Linux x64 Ubuntu 18.04.2 LTS

**Comment by kitao** [comment]
GLFW is not used in the latest Pyxel.
Could you update the module to the latest version?
And it also needs Python 3.7 or higher.
