### ISSUE TITLE
crash on start

### ISSUE THREAD

**Issue by l0stmind** [kitao/pyxel#170]
Hello
After installing Pyxel throught pip (followed the step on github) i have tried to run an example but it won't run.
The cmd line return that:
C:\Users\mel\pyxel_examples>pyxeleditor
Traceback (most recent call last):
  File "c:\users\mel\appdata\local\programs\python\python36-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\mel\appdata\local\programs\python\python36-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\mel\AppData\Local\Programs\Python\Python36-32\Scripts\pyxeleditor.exe\__main__.py", line 9, in <module>
  File "c:\users\mel\appdata\local\programs\python\python36-32\lib\site-packages\pyxel\editor\__init__.py", line 21, in run
    App(filename)
  File "c:\users\mel\appdata\local\programs\python\python36-32\lib\site-packages\pyxel\editor\app.py", line 36, in __init__
    APP_WIDTH, APP_HEIGHT, caption="Pyxel Editor - {}".format(resource_file)
  File "c:\users\mel\appdata\local\programs\python\python36-32\lib\site-packages\pyxel\__init__.py", line 296, in init
    App(module, width, height, caption, scale, palette, fps, border_width, border_color)
  File "c:\users\mel\appdata\local\programs\python\python36-32\lib\site-packages\pyxel\app.py", line 169, in __init__
    self._renderer = Renderer(width, height)
  File "c:\users\mel\appdata\local\programs\python\python36-32\lib\site-packages\pyxel\renderer.py", line 48, in __init__
    self._draw_shader = GLShader(DRAWING_VERTEX_SHADER, DRAWING_FRAGMENT_SHADER)
  File "c:\users\mel\appdata\local\programs\python\python36-32\lib\site-packages\pyxel\gl_wrapper.py", line 12, in __init__
    shaders.compileShader(fragment_shader, gl.GL_FRAGMENT_SHADER),
  File "c:\users\mel\appdata\local\programs\python\python36-32\lib\site-packages\OpenGL\GL\shaders.py", line 197, in compileProgram
    program.check_linked()
  File "c:\users\mel\appdata\local\programs\python\python36-32\lib\site-packages\OpenGL\GL\shaders.py", line 122, in check_linked
    glGetProgramInfoLog( self ),
RuntimeError: Link failure (0): b''

Windows 7 and python 3.6

Could you help me please?
 
Thank you so much.
ludo

**Comment by jaxxgu** [comment]
Hey @l0stmind 
Please check [here](https://github.com/kitao/pyxel#windows) and try Python3.7 or higher

**Comment by l0stmind** [comment]
ho really sorry, i miss that, will try now and give feed back

**Comment by l0stmind** [comment]
finally working, RTFM with attention :) thanks to you...
