### ISSUE TITLE
Crash when shortening the length of sound with undo etc. during playback with the sound editor of pyxeleditor | pyxeleditorのサウンドエディタで再生中に音の長さをundoなどで短くするとクラッシュする

### ISSUE THREAD

**Issue by nnn1590** [kitao/pyxel#209]
**Describe the bug**
pyxeleditorのサウンドエディタで再生中に音の長さをundoなどで短くするとクラッシュします。
Crash when shortening the length of sound with undo etc. during playback with the sound editor of pyxeleditor.

**To Reproduce**
1. `pyxeleditor`を起動する
2. サウンドエディタに切り替える
3. 2つ音符(?)を入れる
4. クラッシュする
<div></div>

1. Start `pyxeleditor`
2. Switch to the sound editor
3. Insert two notes
4. Crash

**Screenshots**
![Record](https://user-images.githubusercontent.com/28985763/69480821-3a811f00-0e4e-11ea-8c24-5b116fb52574.gif)
このGIF動画内では途中で`Ctrl+Z`を押しています。
そのときにクラッシュしています。
In this GIF movie, press `Ctrl+Z` on the way.
Crash at that time.
<details>
<summary>トレースバック | Traceback</summary>

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pyxel/__init__.py", line 561, in draw_wrapper
    draw()
  File "/usr/lib/python3.8/site-packages/pyxel/ui/widget.py", line 297, in draw_widgets
    child.draw_widgets()
  File "/usr/lib/python3.8/site-packages/pyxel/ui/widget.py", line 297, in draw_widgets
    child.draw_widgets()
  File "/usr/lib/python3.8/site-packages/pyxel/ui/widget.py", line 294, in draw_widgets
    self.call_event_handler("draw")
  File "/usr/lib/python3.8/site-packages/pyxel/ui/widget.py", line 136, in call_event_handler
    handler(*args)
  File "/usr/lib/python3.8/site-packages/pyxel/editor/piano_keyboard.py", line 155, in __on_draw
    note = data[self.parent.play_pos] if self.parent.is_playing else self.note
  File "/usr/lib/python3.8/site-packages/pyxel/__init__.py", line 813, in __getitem__
    return self._data_to_list()[ii]
IndexError: list index out of range
```
</details>

**Desktop:**
 - OS: Arch GNU/Linux amd64
 - Browser: Google Chrome
 - Version: 5dec75ded65376930d23523e1fd85a2e91b0bfb8
 - CPU: Intel i7-2700K
 - GPU: AMD ATI Radeon HD 6770
 - Python 3.8.0
 - LXDM + LXDE

**Additional context**
音符を一個だけ置いてから再生中にundoしてもクラッシュしないが消えたはずの音が鳴ります。
If you put only one note and then undo it will not crash, but you will hear an audio that disappeared.

この文章はGoogle 翻訳によって日本語から英語に翻訳されました。
This sentence has been translated from Japanese to English by Google Translate.

**Comment by kitao** [comment]
Fixed in 1.3.0.

1.3.0で修正しました。
