### ISSUE TITLE
image not found error when attempting to import pyxel on mac

### ISSUE THREAD

**Issue by tobynorth99** [kitao/pyxel#219]
Was able to install successfully pyxel after updating my python version.

However now am unable to import pyxel in my python code, or attempt to run any of the examples.
I Am on Mac OS Catalina & the latest python version

I get the following error when attempting to load/import pyxel.

> Traceback (most recent call last):
  File "/Users/tobymardles/Downloads/pyxel-master/pyxel/examples/02_jump_game.py", line 3, in <module>
    import pyxel
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyxel/__init__.py", line 10, in <module>
    from . import core  # type: ignore
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyxel/core/__init__.py", line 40, in <module>
    _lib = _load_library()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyxel/core/__init__.py", line 37, in _load_library
    return cdll.LoadLibrary(lib_path)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ctypes/__init__.py", line 451, in LoadLibrary
    return self._dlltype(name)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyxel/core/bin/macos/libpyxelcore.dylib, 6): Library not loaded: /usr/local/opt/sdl2/lib/libSDL2-2.0.0.dylib
  Referenced from: /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyxel/core/bin/macos/libpyxelcore.dylib
  Reason: image not found

**Comment by Nixonite** [comment]
I got the same issue
