### ISSUE TITLE
Import Failed on Mac OS

### ISSUE THREAD

**Issue by PythonCodeingKing** [kitao/pyxel#249]
This is my problem:
in the TERMINAL:
pip3 install pyxel
in the PYTHON SHELL:
*python prompt* import pyxel
and I get this error:
Traceback (most recent call last):
  File "/Users/elainayenchek/Desktop/Programs/pygame_test.py", line 1, in <module>
    import pyxel
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyxel/__init__.py", line 10, in <module>
    from . import core  # type: ignore
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyxel/core/__init__.py", line 43, in <module>
    _lib = _load_library()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyxel/core/__init__.py", line 40, in _load_library
    return cdll.LoadLibrary(lib_path)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ctypes/__init__.py", line 451, in LoadLibrary
    return self._dlltype(name)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyxel/core/bin/macos/libpyxelcore.dylib, 6): Library not loaded: /usr/local/opt/sdl2/lib/libSDL2-2.0.0.dylib
  Referenced from: /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyxel/core/bin/macos/libpyxelcore.dylib
  Reason: image not found
*python prompt*
I was wondering if I did something wrong.
I'm typing in python 3.8 and so I didn't think the brew install was nesassary.

**Comment by uec-programming** [comment]
I assume you did not download the SDL2 library. Try to install it according to the README.

**Comment by kitao** [comment]
It looks SDL2 library is not installed. Have you installed required libraries specified in README?

**Comment by the6th** [comment]
I had same issue on my mac.

> OSError: dlopen(/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyxel/core/bin/macos/libpyxelcore.dylib, 6): Library not loaded: /usr/local/opt/sdl2/lib/libSDL2-2.0.0.dylib


so, It was success to install pyxel from the source code on github, without pip.

see [Other environment](https://github.com/kitao/pyxel#other-environment) on ReadMe

**Comment by bnidevs** [comment]
I had this issue as well, and I fixed it by reverting back to Pyxel 1.3.9 temporarily

**Comment by hingashi-coder** [comment]
> I had this issue as well, and I fixed it by reverting back to Pyxel 1.3.9 temporarily

It Works fine on my Mac.

**Comment by kitao** [comment]
Installing wan on Mac is changed in 1.5.0. Now you don't need to install any external modules.
