### ISSUE TITLE
Pyxel Error When Importing - Python Version 3.8.3

### ISSUE THREAD

**Issue by sidnand** [kitao/pyxel#257]
**Describe the bug**

When I try to import pyxel, I get this error:

`
Traceback (most recent call last):
  File "__init__.py", line 1, in <module>
    import pyxel
  File "/usr/local/lib/python3.8/site-packages/pyxel/__init__.py", line 10, in <module>
    from . import core  # type: ignore
  File "/usr/local/lib/python3.8/site-packages/pyxel/core/__init__.py", line 43, in <module>
    _lib = _load_library()
  File "/usr/local/lib/python3.8/site-packages/pyxel/core/__init__.py", line 40, in _load_library
    return cdll.LoadLibrary(lib_path)
  File "/usr/local/Cellar/python@3.8/3.8.3_2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ctypes/__init__.py", line 451, in LoadLibrary
    return self._dlltype(name)
  File "/usr/local/Cellar/python@3.8/3.8.3_2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/usr/local/lib/python3.8/site-packages/pyxel/core/bin/macos/libpyxelcore.dylib, 6): Symbol not found: __ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE16find_last_not_ofEPKcmm
  Referenced from: /usr/local/lib/python3.8/site-packages/pyxel/core/bin/macos/libpyxelcore.dylib
  Expected in: /usr/lib/libstdc++.6.dylib
 in /usr/local/lib/python3.8/site-packages/pyxel/core/bin/macos/libpyxelcore.dylib
`

**How I Installed Pyxel**
1. `brew install gcc sdl2 sdl2_image gifsicle`
2. pip3 install pyxel
3. imported pyxel into my file
4. python3 file.py

**Additional context**

Python Version: 3.8.3
Pip Version: 20.0.2

**Comment by jmp** [comment]
I have the same problem on macOS 10.15.6, Python 3.8.3, and pyxel 1.4.1.

So far the only solution I've found is to downgrade to pyxel 1.4.0.

**Comment by Darin1123** [comment]
try older version to solve this problem. I failed when using 1.4.2. However 1.3.9 works. Here is the link about how to install a package with specific version: https://stackoverflow.com/questions/5226311/installing-specific-package-versions-with-pip

**Comment by sidnand** [comment]
> I released Pyxel 1.4.2 and checked it works on clean-installed-macOS 10.15.6.
> And confirmed it works on my second Macbook.
> 
> Could you checke it works or not?

Yes it does!
