### ISSUE TITLE
Shader error when trying to run any of the examples

### ISSUE THREAD

**Issue by ryzy27** [kitao/pyxel#3]
Full error message:

```
Traceback (most recent call last):
  File "I:\WinPython-64bit-3.6.2.0Qt5\scripts\pyxel_examples\01_hello_pyxel.py", line 20, in <module>
    App()
  File "I:\WinPython-64bit-3.6.2.0Qt5\scripts\pyxel_examples\01_hello_pyxel.py", line 6, in __init__
    pyxel.init(160, 120, caption='Hello Pyxel')
  File "I:\WinPython-64bit-3.6.2.0Qt5\python-3.6.2.amd64\lib\site-packages\pyxel\__init__.py", line 33, in init
    border_width, border_color)
  File "I:\WinPython-64bit-3.6.2.0Qt5\python-3.6.2.amd64\lib\site-packages\pyxel\app.py", line 83, in __init__
    self._renderer = Renderer(width, height)
  File "I:\WinPython-64bit-3.6.2.0Qt5\python-3.6.2.amd64\lib\site-packages\pyxel\renderer.py", line 38, in __init__
    DRAWING_FRAGMENT_SHADER)
  File "I:\WinPython-64bit-3.6.2.0Qt5\python-3.6.2.amd64\lib\site-packages\pyxel\glwrapper.py", line 10, in __init__
    shaders.compileShader(vertex_shader, gl.GL_VERTEX_SHADER),
  File "I:\WinPython-64bit-3.6.2.0Qt5\python-3.6.2.amd64\lib\site-packages\OpenGL\GL\shaders.py", line 236, in compileShader
    shaderType,
RuntimeError: ('Shader compile failure (0): b"ERROR: 0:162: \'undefined\' : undeclared identifier \\nERROR: 0:162: \';\' : syntax error parse error\\n"', [b'\n#version 120\n\n#define unpack_4ui_1(x) int(mod(x / 0x1, 0x10));\n#define unpack_4ui_2(x) int(mod(x / 0x10, 0x10));\n#define unpack_4ui_3(x) int(mod(x / 0x100, 0x10));\n#define unpack_4ui_4(x) int(mod(x / 0x1000, 0x10));\n\nconst int TYPE_PIX = 0;\nconst int TYPE_LINE = 1;\nconst int TYPE_RECT = 2;\nconst int TYPE_RECTB = 3;\nconst int TYPE_CIRC = 4;\nconst int TYPE_CIRCB = 5;\nconst int TYPE_BLT = 6;\nconst int TYPE_TEXT = 7;\n\nuniform vec2 u_framebuffer_size;\n\nattribute vec3 a_mode;\nattribute vec4 a_pos;\nattribute vec2 a_size;\nattribute vec4 a_clip;\nattribute vec4 a_pal;\n\nvarying float v_type;\nvarying float v_col;\nvarying float v_image;\nvarying vec2 v_pos1;\nvarying vec2 v_pos2;\nvarying vec2 v_min_pos;\nvarying vec2 v_max_pos;\nvarying vec2 v_size;\nvarying vec2 v_min_clip;\nvarying vec2 v_max_clip;\nvarying float v_pal[16];\n\nvec4 pixelToScreen(vec2 pos)\n{\n    return vec4(pos * 2.0 / u_framebuffer_size - 1.0, 0.0, 1.0);\n}\n\nvoid pix()\n{\n    vec2 p = floor(a_pos.xy + 0.5);\n\n    v_min_pos = v_max_pos = p;\n\n    gl_PointSize = 1.0;\n    gl_Position = pixelToScreen(p);\n}\n\nvoid line()\n{\n    vec2 p1 = floor(a_pos.xy + 0.5);\n    vec2 p2 = floor(a_pos.zw + 0.5);\n\n    v_min_pos = min(p1, p2);\n    v_max_pos = max(p1, p2);\n\n    vec2 d = v_max_pos - v_min_pos;\n\n    if (d.x > d.y)\n    {\n        if (p1.x < p2.x) {\n            v_pos1 = p1;\n            v_pos2 = p2;\n        }\n        else\n        {\n            v_pos1 = p2;\n            v_pos2 = p1;\n        }\n    }\n    else\n    {\n        if (p1.y < p2.y)\n        {\n            v_pos1 = p1;\n            v_pos2 = p2;\n        }\n        else\n        {\n            v_pos1 = p2;\n            v_pos2 = p1;\n        }\n    }\n\n    gl_PointSize = max(d.x, d.y) + 1.0;\n    gl_Position = pixelToScreen(v_min_pos + (gl_PointSize - 1.0) * 0.5);\n}\n\nvoid rect_rectb()\n{\n    vec2 p1 = floor(a_pos.xy + 0.5);\n    vec2 p2 = floor(a_pos.zw + 0.5);\n\n    v_min_pos = min(p1, p2);\n    v_max_pos = max(p1, p2);\n\n    vec2 s = v_max_pos - v_min_pos + 1.0;\n\n    gl_PointSize = max(s.x, s.y);\n    gl_Position = pixelToScreen(v_min_pos + (gl_PointSize - 1.0) * 0.5);\n}\n\nvoid circ_circb()\n{\n    vec2 p = floor(a_pos.xy + 0.5);\n    float r = floor(a_size.x + 0.5);\n\n    v_pos1 = p;\n    v_min_pos = p - r;\n    v_max_pos = p + r;\n    v_size.x = r;\n\n    gl_PointSize = r * 2.0 + 1.0;\n    gl_Position = pixelToScreen(p);\n}\n\nvoid blt()\n{\n    vec2 p1 = floor(a_pos.xy + 0.5);\n    vec2 p2 = floor(a_pos.zw + 0.5);\n    vec2 s = floor(a_size + 0.5);\n    vec2 abs_s = abs(s);\n\n    v_pos1 = p1;\n    v_pos2 = p2;\n    v_min_pos = p1;\n    v_max_pos = p1 + abs_s - 1.0;\n    v_size = s;\n\n    gl_PointSize = max(abs_s.x, abs_s.y);\n    gl_Position = pixelToScreen(v_min_pos + (gl_PointSize - 1.0) * 0.5);\n}\n\nvoid text()\n{\n    v_image = 5 - 1;\n    vec2 p1 = floor(a_pos.xy + 0.5);\n    vec2 p2 = vec2(mod(a_pos.z, 64) * 4, floor(a_pos.z / 64) * 6);\n    vec2 s = vec2(4, 6);\n    vec2 abs_s = abs(s);\n\n    v_pos1 = p1;\n    v_pos2 = p2;\n    v_min_pos = p1;\n    v_max_pos = p1 + abs_s - 1.0;\n    v_size = s;\n\n    gl_PointSize = max(abs_s.x, abs_s.y);\n    gl_Position = pixelToScreen(v_min_pos + (gl_PointSize - 1.0) * 0.5);\n}\n\nvoid main()\n{\n    v_type = a_mode.x;\n    v_col = a_mode.y;\n    v_image = a_mode.z;\n\n    v_pal[0] = unpack_4ui_1(a_pal.x);\n    v_pal[1] = unpack_4ui_2(a_pal.x);\n    v_pal[2] = unpack_4ui_3(a_pal.x);\n    v_pal[3] = unpack_4ui_4(a_pal.x);\n    v_pal[4] = unpack_4ui_1(a_pal.y);\n    v_pal[5] = unpack_4ui_2(a_pal.y);\n    v_pal[6] = unpack_4ui_3(a_pal.y);\n    v_pal[7] = unpack_4ui_4(a_pal.y);\n    v_pal[8] = unpack_4ui_1(a_pal.z);\n    v_pal[9] = unpack_4ui_2(a_pal.z);\n    v_pal[10] = unpack_4ui_3(a_pal.z);\n    v_pal[11] = unpack_4ui_4(a_pal.z);\n    v_pal[12] = unpack_4ui_1(a_pal.w);\n    v_pal[13] = unpack_4ui_2(a_pal.w);\n    v_pal[14] = unpack_4ui_3(a_pal.w);\n    v_pal[15] = unpack_4ui_4(a_pal.w);\n\n    if (v_type == TYPE_PIX) { pix(); }\n    else if (v_type == TYPE_LINE) { line(); }\n    else if (v_type == TYPE_RECT || v_type == TYPE_RECTB) { rect_rectb(); }\n    else if (v_type == TYPE_CIRC || v_type == TYPE_CIRCB) { circ_circb(); }\n    else if (v_type == TYPE_BLT) { blt(); }\n    else if (v_type == TYPE_TEXT) { text(); }\n    else { gl_Position = vec4(0.0, 0.0, 0.0, 1.0); }\n\n    vec2 p1 = floor(a_clip.xy + 0.5);\n    vec2 p2 = floor(a_clip.zw + 0.5);\n\n    v_min_clip = max(min(p1, p2), v_min_pos);\n    v_max_clip = min(max(p1, p2), v_max_pos);\n}\n'], GL_VERTEX_SHADER)
```

Do you have a solution for that problem?

**Comment by golebiewsky** [comment]
Try using 'normal' Python instead of WinPython and post results, it will help to identify the issue.

**Comment by kitao** [comment]
Thank you for the report!
It seems that the define macros in the shader have unnecessary semicolons at the end of each line and those are detected as errors in some environment.

**Comment by kitao** [comment]
I removed the unnecessary semicolons and released it as v0.7.2.
Can anyone try it?

**Comment by ryzy27** [comment]
I tried v0.7.2. Unfortunately it does not work with WinPython, nor Python 3.7. I still get the same error. 

My laptop specs are: i3 2330m, Nvidia GT 540M.

In about 2 weeks I'll have access to my PC and I'll check if I get that error there too.

**Comment by kitao** [comment]
I added the glfw version check in 0.7.9.
So I'll close this (relatively) old issue one and see the situation.

**Comment by ryzy27** [comment]
I tried running examples on my PC, no problems there.
However with the laptop, I still get that error. Could this be because of integrated Intel graphics card?
