### ISSUE TITLE
install_pyxel_examples fails : Symbol not found : Mac  pyxel 1.4.3

### ISSUE THREAD

**Issue by DannyCork** [kitao/pyxel#308]
**Describe the bug**
install_pyxel_examples fails

**To Reproduce**
1. Installed all dependancies....
```
% brew install python3 gcc sdl2 sdl2_image gifsicle
Warning: python@3.9 3.9.5 is already installed and up-to-date.
To reinstall 3.9.5, run:
  brew reinstall python@3.9
Warning: gcc 11.1.0_1 is already installed and up-to-date.
To reinstall 11.1.0_1, run:
  brew reinstall gcc
Warning: sdl2 2.0.14_1 is already installed and up-to-date.
To reinstall 2.0.14_1, run:
  brew reinstall sdl2
Warning: sdl2_image 2.0.5 is already installed and up-to-date.
To reinstall 2.0.5, run:
  brew reinstall sdl2_image
Warning: gifsicle 1.92 is already installed and up-to-date.
To reinstall 1.92, run:
  brew reinstall gifsicle
```
2. restarted the terminal

3. installed pixel
```
% pip3 install -U pyxel
Requirement already satisfied: pyxel in /usr/local/lib/python3.9/site-packages (1.4.3)
```
4. Attempted to install the examples
```
% install_pyxel_examples 
Traceback (most recent call last):
  File "/usr/local/bin/install_pyxel_examples", line 5, in <module>
    from pyxel.examples import install
  File "/usr/local/lib/python3.9/site-packages/pyxel/__init__.py", line 10, in <module>
    from . import core  # type: ignore
  File "/usr/local/lib/python3.9/site-packages/pyxel/core/__init__.py", line 42, in <module>
    _lib = _load_library()
  File "/usr/local/lib/python3.9/site-packages/pyxel/core/__init__.py", line 39, in _load_library
    return cdll.LoadLibrary(lib_path)
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ctypes/__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/usr/local/lib/python3.9/site-packages/pyxel/core/bin/macos/libpyxelcore.dylib, 6): Symbol not found: __ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE16find_last_not_ofEPKcmm
  Referenced from: /usr/local/lib/python3.9/site-packages/pyxel/core/bin/macos/libpyxelcore.dylib
  Expected in: /usr/lib/libstdc++.6.dylib
 in /usr/local/lib/python3.9/site-packages/pyxel/core/bin/macos/libpyxelcore.dylib
```
5. Reinstalled sdl2
```
brew reinstall sdl2                              
==> Downloading https://ghcr.io/v2/homebrew/core/sdl2/manifests/2.0.14_1
Already downloaded: /Users/x/Library/Caches/Homebrew/downloads/126fe5ba8860c768aaf86014de0ca0cd0c7d77dd901f69ca88a367575d0e3d9c--sdl2-2.0.14_1.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/sdl2/blobs/sha256:ccde7145d4334d9274f9588e6b841bf3749729682e1d25f590bdcf7994dfdd8
Already downloaded: /Users/x/Library/Caches/Homebrew/downloads/396e9c87f43a6f74b3cdc7c4f8e466f1817cfc57c14f8f1258dfc836f88ca242--sdl2--2.0.14_1.big_sur.bottle.tar.gz
==> Reinstalling sdl2 
==> Pouring sdl2--2.0.14_1.big_sur.bottle.tar.gz
🍺  /usr/local/Cellar/sdl2/2.0.14_1: 91 files, 5.1MB
```

6. tried install_pyxel_examples but it fails again as as above.

**Expected behavior**
Should install.

**Desktop (please complete the following information):**
Mac Big sur 11.4 (20F71)

% pip3 list pyxel | grep pyxel
pyxel                     1.4.3

**Comment by DannyCork** [comment]
appears similar to #257

**Comment by ryohji** [comment]
This issue seems as same as #302.

I wrote a way to solve this issue in its comment, https://github.com/kitao/pyxel/issues/302?_pjax=%23repo-content-pjax-container#issuecomment-894804009.

**Comment by kitao** [comment]
In 1.5.0, the installing way on Mac is changed. Please try.
