### ISSUE TITLE
The wheel in PyPI doesn't work with Apple M1

### ISSUE THREAD

**Issue by akheron** [kitao/pyxel#312]
**Describe the bug**
The provided wheel doesn't work on the newest Apple M1 architecture.

**To Reproduce**
```
$ python3 -m venv venv
$ ./venv/bin/pip install pyxel
Collecting pyxel
  Using cached pyxel-1.4.3-py3-none-any.whl (5.3 MB)
Installing collected packages: pyxel
Successfully installed pyxel-1.4.3
$ ./venv/bin/pyxeleditor 
Traceback (most recent call last):
  File "/Users/akheron/code/peli/./venv/bin/pyxeleditor", line 5, in <module>
    from pyxel.editor import run
  File "/Users/akheron/code/peli/venv/lib/python3.9/site-packages/pyxel/__init__.py", line 10, in <module>
    from . import core  # type: ignore
  File "/Users/akheron/code/peli/venv/lib/python3.9/site-packages/pyxel/core/__init__.py", line 42, in <module>
    _lib = _load_library()
  File "/Users/akheron/code/peli/venv/lib/python3.9/site-packages/pyxel/core/__init__.py", line 39, in _load_library
    return cdll.LoadLibrary(lib_path)
  File "/opt/homebrew/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ctypes/__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "/opt/homebrew/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Users/akheron/code/peli/venv/lib/python3.9/site-packages/pyxel/core/bin/macos/libpyxelcore.dylib, 6): no suitable image found.  Did find:
	/Users/akheron/code/peli/venv/lib/python3.9/site-packages/pyxel/core/bin/macos/libpyxelcore.dylib: mach-o, but wrong architecture
	/Users/akheron/code/peli/venv/lib/python3.9/site-packages/pyxel/core/bin/macos/libpyxelcore.dylib: mach-o, but wrong architecture
```

**Expected behavior**
The editor should start.

**Desktop (please complete the following information):**
 - OS: macOS Big Sur 11.4
 - Version: pyxel 1.4.3

**Comment by akheron** [comment]
Compiling the core with `CC=g++-11` and running `python setup.py install` makes it work.

**Comment by humrochagf** [comment]
Yeah, M1 architecture is arm based, so currently precompiled builds from other mac versions will not work out of the box. Not sure how pypi is dealing with this new mac architecture,  but eventually packaging of the next versions will need an architecture check step.

**Comment by kitao** [comment]
Please try Pyxel 1.5.0. I got reports that it works on M1 Mac from users
