### ISSUE TITLE
Fails with ImportError on Python 3.10

### ISSUE THREAD

**Issue by jaraco** [kitao/pyxel#313]
**Describe the bug**
Attempting to import pyxel on Python 3.10 fails when the deprecated usage of MutableSequence is queried.

```
~ $ ~/.local/pipx/venvs/pyxel/bin/python -c 'import pyxel'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/jaraco/.local/pipx/venvs/pyxel/lib/python3.10/site-packages/pyxel/__init__.py", line 6, in <module>
    from collections import MutableSequence
ImportError: cannot import name 'MutableSequence' from 'collections' (/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/collections/__init__.py)
```

**To Reproduce**
1. python3.10 -m pip install pyxel
2. python3.10 -c "import pyxel"

**Expected behavior**
Pyxel should import.

**Comment by jaraco** [comment]
The same error can be seen on Python 3.9 by passing `-We` to Python (error on warnings):

```
~ $ python3.9 -m pip-run -q pyxel -- -We -c 'import pyxel'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/pip-run-5xahmdfe/pyxel/__init__.py", line 6, in <module>
    from collections import MutableSequence
  File "<frozen importlib._bootstrap>", line 1055, in _handle_fromlist
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/collections/__init__.py", line 62, in __getattr__
    warnings.warn("Using or importing the ABCs from 'collections' instead "
DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
```

**Comment by kitao** [comment]
Please try 1.5.0.

**Comment by jaraco** [comment]
Works great! Thanks.
