### ISSUE TITLE
linux file won't run after using pyinstaller --onefile [file.py]

### ISSUE THREAD

**Issue by LetsPlayPong** [kitao/pyxel#364]
newb — Today at 2:28 PM
desktop:~/Documents/pyxel/pyxel_examples/dist$ ./01_hello_pyxel
thread '<unnamed>' panicked at 'Unable to open file '/tmp/_MEIWDGn96/pyxel/editor/assets/editor_220x160.png'', engine/src/image.rs:43:33
note: run with RUST_BACKTRACE=1 environment variable to display a backtrace
Traceback (most recent call last):
  File "01_hello_pyxel.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 476, in exec_module
  File "pyxel/init.py", line 15, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 476, in exec_module
  File "pyxel/cli.py", line 11, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 476, in exec_module
  File "pyxel/editor/init.py", line 2, in <module>
File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 476, in exec_module
  File "pyxel/editor/app.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 476, in exec_module
  File "pyxel/editor/image_editor.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 476, in exec_module
  File "pyxel/editor/canvas_panel.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 476, in exec_module
  File "pyxel/editor/settings.py", line 6, in <module>
pyo3_runtime.PanicException: Unable to open file '/tmp/_MEIWDGn96/pyxel/editor/assets/editor_220x160.png'
[6401] Failed to execute script '01_hello_pyxel' due to unhandled exception!
merwok — Today at 2:29 PM
what was the package command used to build the program?
newb— Today at 2:29 PM
pyinstaller --onefile 01_hello_pyxel.py 
merwok — Today at 2:33 PM
I see!  the reworking of pyxel in a recent version means that importing pyxel tries to import the cli submodules which imports the editor submodule which tries to load an image and fails
please open a bug report on github
this should be fixed, pyxel/__init__.py should not import cli/editor/other things that are not the core game functions and classes

**Comment by DiddiLeija** [comment]
Just for the record, this was first reported in the Discord Pyxel server in English, at `#help`.

**Comment by kitao** [comment]
New Pyxel doesn't support PyInstaller.
Pyxel's policy is to share a Pyxel applications as .pyxapp format. Because it works on every platform.
You can bundle the standalone version of Pyxel with your application.
In the future, I may provide a way to combine the Pyxel and .pyxapp as one file.

**Comment by merwok** [comment]
Importing the `cli` submodule in `__init__` is unnecessary (you can support `python -m pyxel` with a `__main__` module, or `pxyel` command with an entry point `pyxel.cli:cli`), so why not remove it?  Importing pyxel game functions should not import editor code and try to load assets.  If people want to use regular Python tools to package pyxel runner with their game, why make it harder for them?

**Comment by kitao** [comment]
In the case, users may not be possible to load Pyxel resources as well. Is
my understanding is correct? Or is it it just the simple problem that it is
troublesome to include editor asset?

2022年1月11日(火) 0:29 Éric ***@***.***>:

**Comment by merwok** [comment]
Message 1: The various tools use a mix of automatic detection of imported modules and manual config to determine what files should be included in their artifact.  (When pyxel used pyinstaller, it passed extra params to have the asset file included.)  So pyxel could help people who use these tools by separating its submodules into core things (game functions) and editor/ui.

Message 2: Sorry, we have a small misunderstanding: I mentioned `__main__` as a way to support `python -m pyxel`, which can be useful during development or in other cases.  It is separate from the `pyxel` script, which can be defined with an entry point like `'pyxel.cli:cli'` which is handled by setuptools/pip to create a script that invokes the specified function.  No need to import inside `__init__.

**Comment by kitao** [comment]
Importing tool-related module can be separated. My concern I mentioned
earlier means that PyInstaller works if only tool-related module is
separated or not.Have you tried that in Pyxel 1.5+?

2022年1月11日(火) 3:29 Éric ***@***.***>:

**Comment by merwok** [comment]
I am not using one-file-package tools at the moment (I’m not the person with the original problem)

**Comment by kitao** [comment]
I removed the cli function from pyxel module to avoid to be imported initially in the develop brunch.
But I’m not sure PyInstaller works.

**Comment by merwok** [comment]
I tried it a couple times with version 1.4, I will have a look with current version when I have the time!
