### ISSUE TITLE
Debian 9 fail on run any example

### ISSUE THREAD

**Issue by nenodias** [kitao/pyxel#39]
`Traceback (most recent call last):
  File "/home/user/Downloads/python/exemplo.py", line 3, in <module>
    pyxel.init(160, 120)
  File "/home/user/.local/lib/python3.5/site-packages/pyxel/__init__.py", line 27, in init
    border_width, border_color)
  File "/home/user/.local/lib/python3.5/site-packages/pyxel/app.py", line 79, in __init__
    self._renderer = Renderer(width, height)
  File "/home/user/.local/lib/python3.5/site-packages/pyxel/renderer.py", line 28, in __init__
    DRAWING_FRAGMENT_SHADER)
  File "/home/user/.local/lib/python3.5/site-packages/pyxel/glwrapper.py", line 12, in __init__
    shaders.compileShader(fragment_shader, gl.GL_FRAGMENT_SHADER))
  File "/home/user/.local/lib/python3.5/site-packages/OpenGL/GL/shaders.py", line 196, in compileProgram
    program.check_validate()
  File "/home/user/.local/lib/python3.5/site-packages/OpenGL/GL/shaders.py", line 108, in check_validate
    glGetProgramInfoLog( self ),
RuntimeError: Validation failure (0):
`
I'm try with Python 3.5.3 and Python 3.5.5 |Anaconda, Inc. (By anaconda install)

**Comment by AndrewNelis** [comment]
This looks the same as #23

**Comment by nenodias** [comment]
On this issue [#23](https://github.com/kitao/pyxel/issues/23l)  kitao says the was fixed on 0.7.5, but I was do a git clone of master branch (after I tried with develop, same result), still not works

**Comment by AndrewNelis** [comment]
Ok.

I'd suggest making the same change to `glwrapper.py`, adding the "validate=False" argument so you might more information out of the traceback:

```python
class GLShader:
    def __init__(self, vertex_shader, fragment_shader):
        self._program = shaders.compileProgram(
            shaders.compileShader(vertex_shader, gl.GL_VERTEX_SHADER),
            shaders.compileShader(fragment_shader, gl.GL_FRAGMENT_SHADER), validate=False)
```

**Comment by nenodias** [comment]
I found the problem, pyxel library was on $HOME/.local/lib/python3.5, which I was install with pip.
I remove that folder, and now it's picking the library from right place, and works.

Thanks
