### ISSUE TITLE
Empty assets directory after install_pyxel_examples

### ISSUE THREAD

**Issue by golebiewsky** [kitao/pyxel#4]
Downloaded the examples using install_pyxel_examples command, the python files are there, but assets dir is empty, so you need to download them from github.

```
Traceback (most recent call last):
  File "02_jump_game.py", line 159, in <module>
    App()
  File "02_jump_game.py", line 9, in __init__
    pyxel.image(0).load(0, 0, 'assets/jump_game_160x120.png')
  File "C:\Users\golebiewski\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pyxel\image.py", line 46, in load
    pil_image = PIL.Image.open(filename).convert('RGB')
  File "C:\Users\golebiewski\AppData\Local\Programs\Python\Python36-32\lib\site-packages\PIL\Image.py", line 2580, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'assets/jump_game_160x120.png'
```

**Comment by vesche** [comment]
It would seem that the package on PyPi hasn't been updated with assets, the author @kitao just needs to update the package. :)

```
$ pip download pyxel
...
$ unzip pyxel-0.7.0-py3-none-any.whl
...
$ ls pyxel/examples/
01_hello_pyxel.py  02_jump_game.py  03_draw_api.py  04_sound_api.py  __init__.py
```

**Comment by kitao** [comment]
Sorry, I fixed to include the necessary files. Please try to upgrade via PyPI
