### ISSUE TITLE
ImportError: libSDL2-2.0.so.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by KonstantinKlepikov** [kitao/pyxel#453]
```sh
pyxel copy_examples

Traceback (most recent call last):
  File "/home/kklepikov/_code_/pixel-proj/venv/bin/pyxel", line 5, in <module>
    from pyxel.cli import cli
  File "/home/kklepikov/_code_/pixel-proj/venv/lib/python3.10/site-packages/pyxel/__init__.py", line 1, in <module>
    from .pyxel_extension import *  # type: ignore  # noqa F403
ImportError: libSDL2-2.0.so.0: cannot open shared object file: No such file or directory
```

libsdl-ttf2.0-0 is installed

Pop!_OS 22.04 LTS, python 3.10

all other commands from pyxel cli makes same error

**Comment by merwok** [comment]
does libsdl-ttf2.0 depend on libsdl2 ?

**Comment by KonstantinKlepikov** [comment]
@merwok you right - not depend :)
