### ISSUE TITLE
demo of 30 Seconds Of Daylight is crashing

### ISSUE THREAD

**Issue by KellyThomas** [kitao/pyxel#506]
Immediately after clicking on 'Click to start' it shows this exception message

```
Traceback (most recent call last):
  File "/lib/python311.zip/_pyodide/_base.py", line 499, in eval_code
    .run(globals, locals)
     ^^^^^^^^^^^^^^^^^^^^
  File "/lib/python311.zip/_pyodide/_base.py", line 340, in run
    coroutine = eval(self.code, globals, locals)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "", line 3, in 
  File "/lib/python3.11/site-packages/pyxel/cli.py", line 215, in play_pyxel_app
    runpy.run_path(startup_script_file, run_name="__main__")
  File "", line 291, in run_path
  File "", line 98, in _run_module_code
  File "", line 88, in _run_code
  File "/tmp/.pyxel/play/42/30SecondsOfDaylight/src/main.py", line 37, in 
    App()
  File "/tmp/.pyxel/play/42/30SecondsOfDaylight/src/main.py", line 17, in __init__
    pyxel.load("../res/rpg01.pyxres")
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: Error { inner: Error { inner: TomlError { message: "missing field `colors`", original: Some("format_version = 2\n\n[[images]]\nwidth = 256\nheight = 256\ndata = [[0, 6, 6, 6, <snip>
```
I've snipped the message, the original is 50kB.

Tested and reproduced with Firefox 120.0.1 and Edge 120.0.2210.61

**Comment by kitao** [comment]
I accidentally uploaded the new resource format to the main branch.
And restored now.

**Comment by KellyThomas** [comment]
cheers, its working great now.
