### ISSUE TITLE
Pyxel crash when starting edit or hello world example

### ISSUE THREAD

**Issue by Shoozza** [kitao/pyxel#516]
pyxel 2.0.6 not running on old pc with windows 8.1.
pyxel 2.0.5 still works fine.

Error:
```
> pyxel edit
thread '<unnamed>' panicked at C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\glow-0.13.1\src\native.rs:56:13:
Reading GL_VERSION failed. Make sure there is a valid GL context currently active.
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\start\AppData\Roaming\Python\Python312\Scripts\pyxel.exe\__main__.py", line 7, in <module>
  File "C:\Users\start\AppData\Roaming\Python\Python312\site-packages\pyxel\cli.py", line 53, in cli
    command[1](*sys.argv[2:])
  File "C:\Users\start\AppData\Roaming\Python\Python312\site-packages\pyxel\cli.py", line 228, in edit_pyxel_resource
    pyxel.editor.App(pyxel_resource_file, starting_editor)
  File "C:\Users\start\AppData\Roaming\Python\Python312\site-packages\pyxel\editor\app.py", line 42, in __init__
    pyxel.init(APP_WIDTH, APP_HEIGHT, quit_key=pyxel.KEY_NONE)
pyo3_runtime.PanicException: Reading GL_VERSION failed. Make sure there is a valid GL context currently active.
```

**Comment by kitao** [comment]
Please let me say that Windows 8.1 is unsupported.
