### ISSUE TITLE
after install pyxel in Linux, it shows me "No module named 'pyxel'"

### ISSUE THREAD

**Issue by xukongwen** [kitao/pyxel#72]
what got wrong?
i can't run any examples.

please help.

**Comment by butterfly-pn** [comment]
what is your OS?

**Comment by jamesguessis** [comment]
What versions of python are installed?

**Comment by cmcknight** [comment]
Suggestions:

1. Create a venv for Python 3 in your pyxel directory. (python3 -m venv directory)
2. Change to that directory (cd directory_name)
3. Activate the venv (source bin/activate)
4. Validate that you are now using Python 3 (python -V)
5. Update pip   (pip install pip --upgrade)
6. Install pyxel  (pip install pyxel)
7. Install examples (install_pyxel_examples)

Be sure you have installed all of the required libraries per the wiki). Those were the steps I followed and everything worked.

**Comment by xukongwen** [comment]
hi cmcknight, i install the pyxel finally, i find i have python3.6 and python3.7 on my linux,
and i use 'python3.7 -m pip install " and it worked.

but when i test any examples, it goes:
Traceback (most recent call last):
  File "hi.py", line 20, in <module>
    App()
  File "hi.py", line 6, in __init__
    pyxel.init(160, 120, caption="Hello Pyxel")
  File "/home/xukongwen/.local/lib/python3.7/site-packages/pyxel/__init__.py", line 24, in init
    from .app import App
  File "/home/xukongwen/.local/lib/python3.7/site-packages/pyxel/app.py", line 13, in <module>
    import PIL.Image
  File "/usr/lib/python3/dist-packages/PIL/Image.py", line 60, in <module>
    from . import _imaging as core
ImportError: cannot import name '_imaging' from 'PIL' (/usr/lib/python3/dist-packages/PIL/__init__.py)
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 24, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'

Original exception was:
Traceback (most recent call last):
  File "hi.py", line 20, in <module>
    App()
  File "hi.py", line 6, in __init__
    pyxel.init(160, 120, caption="Hello Pyxel")
  File "/home/xukongwen/.local/lib/python3.7/site-packages/pyxel/__init__.py", line 24, in init
    from .app import App
  File "/home/xukongwen/.local/lib/python3.7/site-packages/pyxel/app.py", line 13, in <module>
    import PIL.Image
  File "/usr/lib/python3/dist-packages/PIL/Image.py", line 60, in <module>
    from . import _imaging as core
ImportError: cannot import name '_imaging' from 'PIL' (/usr/lib/python3/dist-packages/PIL/__init__.py)



why?

**Comment by Rutrus** [comment]
Did you tried...?
`python3.7 -m pip install pyxel`

That worked for me.

**Comment by NgyAnthony** [comment]
> Suggestions:
> 
> 1. Create a venv for Python 3 in your pyxel directory. (python3 -m venv directory)
> 2. Change to that directory (cd directory_name)
> 3. Activate the venv (source bin/activate)
> 4. Validate that you are now using Python 3 (python -V)
> 5. Update pip   (pip install pip --upgrade)
> 6. Install pyxel  (pip install pyxel)
> 7. Install examples (install_pyxel_examples)
> 
> Be sure you have installed all of the required libraries per the wiki). Those were the steps I followed and everything worked.

Issue has been fixed for me by following these steps.
