### ISSUE TITLE
crash when double click the title bar

### ISSUE THREAD

**Issue by deluxghost** [kitao/pyxel#77]
OS: Windows 10 1803
Pyxel: 0.8.2
If i double click the title bar (maximize the window in Windows) immediately after the game launched (without any clicking), the game will crash with exceptions:

```python
Traceback (most recent call last):
  File ".\game.py", line 71, in <module>
    Game()
  File ".\game.py", line 33, in __init__
    pyxel.run(self.update, self.draw)
  File "C:\Program Files\Python37\lib\site-packages\pyxel\app.py", line 228, in run
    main_loop()
  File "C:\Program Files\Python37\lib\site-packages\pyxel\app.py", line 216, in main_loop
    glfw.poll_events()
  File "C:\Program Files\Python37\lib\site-packages\glfw\__init__.py", line 1337, in poll_events
    _glfw.glfwPollEvents()
  File "C:\Program Files\Python37\lib\site-packages\glfw\__init__.py", line 515, in errcheck
    _reraise(exc[1], exc[2])
  File "C:\Program Files\Python37\lib\site-packages\glfw\__init__.py", line 45, in _reraise
    raise exception.with_traceback(traceback)
  File "C:\Program Files\Python37\lib\site-packages\glfw\__init__.py", line 494, in callback_wrapper
    return func(*args, **kwargs)
  File "C:\Program Files\Python37\lib\site-packages\pyxel\app.py", line 370, in _mouse_button_callback
    if self._key_state[button] == self._module.frame_count:
KeyError: 1004
```

self._key_state is empty when this bug appears

but if i click the game window body first, then double click the title bar, game wont crash.

maybe pyxel should also check the _key_state content in these callback functions

**Comment by kitao** [comment]
Thank you for report!
I fixed this bug in 0.8.3 and released it.
