### ISSUE TITLE
macOS: Pressing the 'fn' key causes Pyxel to crash

### ISSUE THREAD

**Issue by sacredhotdog** [kitao/pyxel#94]
I discovered this by accident when using the editor, but based on where & why the error occurs, it looks like it would be a problem in general.

Pressing the 'fn' key on a Mac keyboard  causes the following error:
```
Traceback (most recent call last):
  File "venv/bin/pyxeleditor", line 11, in <module>
    load_entry_point('pyxel', 'console_scripts', 'pyxeleditor')()
  File "/Users/_/Projects/pyxel/pyxel/editor/__init__.py", line 9, in run
    App(sys.argv[1])
  File "/Users/_/Projects/pyxel/pyxel/editor/app.py", line 95, in __init__
    pyxel.run(self.update_widgets, self.draw_widgets)
  File "/Users/_/Projects/pyxel/pyxel/app.py", line 252, in run
    main_loop()
  File "/Users/_/Projects/pyxel/pyxel/app.py", line 240, in main_loop
    glfw.poll_events()
  File "/Users/_/Projects/pyxel/venv/lib/python3.7/site-packages/glfw/__init__.py", line 1337, in poll_events
    _glfw.glfwPollEvents()
  File "/Users/_/Projects/pyxel/venv/lib/python3.7/site-packages/glfw/__init__.py", line 515, in errcheck
    _reraise(exc[1], exc[2])
  File "/Users/_/Projects/pyxel/venv/lib/python3.7/site-packages/glfw/__init__.py", line 45, in _reraise
    raise exception.with_traceback(traceback)
  File "/Users/_/Projects/pyxel/venv/lib/python3.7/site-packages/glfw/__init__.py", line 494, in callback_wrapper
    return func(*args, **kwargs)
  File "/Users/_/Projects/pyxel/pyxel/app.py", line 356, in _key_callback
    if self._key_state[key] == pyxel.frame_count:
KeyError: -1
```

The cause seems to be that this key only triggers a `glfw.RELEASE` and not a `glfw.PRESS` action. Without `_key_state` being pre-populated by the `glfw.PRESS` event, this results in the above error when executing `self._key_state[key]`.

This is on macOS Mojave - I'm not sure if this would affect other Mac OS versions tbh.

**Comment by Jengah** [comment]
@sacredhotdog can confirm that it affects other macOS versions. Same error on macOS Sierra.

**Comment by kitao** [comment]
Thank you for checking.
In 0.9.2, this bug should be fixed.
@Jengah Which version of Pyxel do you use?

**Comment by Jengah** [comment]
Was on an older version. Missed the merged PR reference. Everything looks good 👍
