### ISSUE TITLE
Crash to desktop with glfw.GLFWError: (65544) when entering fullscreen

### ISSUE THREAD

**Issue by Noah-Maze** [kitao/pyxel#99]
Full error:
```
Traceback (most recent call last):
  File "app.py", line 34, in <module>
    App()
  File "app.py", line 22, in __init__
    pyxel.run(self.update, self.draw)
  File "C:\[__redacted__]\pyxel\app.py", line 252, in run
    main_loop()
  File "C:\[__redacted__]\pyxel\app.py", line 244, in main_loop
    self._update_frame()
  File "C:\[__redacted__]\pyxel\app.py", line 432, in _update_frame
    self._check_special_input()
  File "C:\[__redacted__]\pyxel\app.py", line 506, in _check_special_input
    self._toggle_fullscreen()
  File "C:\[__redacted__]\pyxel\app.py", line 501, in _toggle_fullscreen
    glfw.set_window_monitor(self._window, monitor, 0, 0, *size, 0)
  File "C:\[__redacted__]\AppData\Local\Programs\Python\Python37\lib\site-packages\glfw\__init__.py", line 2134, in set_window_monitor
    xpos, ypos, width, height, refresh_rate)
  File "C:\[__redacted__]\AppData\Local\Programs\Python\Python37\lib\site-packages\glfw\__init__.py", line 515, in errcheck
    _reraise(exc[1], exc[2])
  File "C:\[__redacted__]\AppData\Local\Programs\Python\Python37\lib\site-packages\glfw\__init__.py", line 45, in _reraise
    raise exception.with_traceback(traceback)
  File "C:\[__redacted__]\AppData\Local\Programs\Python\Python37\lib\site-packages\glfw\__init__.py", line 494, in callback_wrapper
    return func(*args, **kwargs)
  File "C:\[__redacted__]\AppData\Local\Programs\Python\Python37\lib\site-packages\glfw\__init__.py", line 668, in _raise_glfw_errors_as_exceptions
    raise GLFWError(message)
glfw.GLFWError: (65544) b'Win32: Failed to set video mode'
```
I managed to fix this on my machine by setting the refresh rate to `60` (instead of `0`) in the `set_window_monitor` call, but I don't know enough about glfw to know for sure if this was the right thing to do.  I'm going to open up a merge request in a minute so we can discuss it.  

Thanks!

**Comment by kitao** [comment]
Thank you.
Fixed in 0.9.4
